### PR TITLE
Switch human logger from JSON to logfmt

### PR DESCRIPTION
**Pull request by ammario**
new:
Screenshot 2023-05-08 at 8 34 27 PM

old:
Screenshot 2023-05-08 at 2 45 36 PM

---

cc @nhooyr, see https://github.com/coder/coder/issues/7451 for context.

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]

**Comment by nhooyr** [comment]
The lack of syntax highlighting makes me really sad :(

**Comment by alixander** [comment]
i just upgrade deps and was surprised at this change. in particular, JSON as a slog field is no longer readable. 

Old:

Screen Shot 2023-05-08 at 10 41 48 PM

New:

Screen Shot 2023-05-08 at 10 42 10 PM


anyway, we can just peg to old version, or is there a config to switch to JSON again @nhooyr ?

**Comment by nhooyr** [comment]
@alixander just peg to old version. This change wasn't made in consultation with me. I disagree with it.

**Comment by ammario** [comment]
@alixander and @nhooyr — sorry for the abrupt merge, I should've kept this open for longer.

This raises a good moment to discuss the future of this project. Is the lack of JSON highlighting your main issue with the change, or is Coder's general goal of moving towards stdlib slog against your's?

**Comment by coadler** [comment]
Could we just have different sloggers for the old human fmt and logfmt?

**Comment by nhooyr** [comment]
I'd prefer @coadler's suggestion for now. If this new slogger came in a different package that's cool, I'm not opposed to more options and supporting stdlib slog seems like a good idea on the face of it.

I'm not too familiar with the stlib slog. I'm in Ontario right now visiting my ailing mum. I don't have the time right now to look into it or the issue you made at https://github.com/coder/coder/issues/7451. When I get back to Kaslo I'll look into it.

**Pull request merged**
